language: node_js

node_js:
  - '10.15.3'

cache:
  directories:
    -"node_modules"

install:
  - npm install -q --no-color --no-progress

before_script: chmod 0777 ./node_modules/.bin/mocha
  
script:
  - npm run test

after_success:
  - npm run coverage
  - npm run report-coverage
