
language: node_js
sudo: false
node_js:
  - '10.15.3'
 cache:
  directories:
  - node_modules
addons:
  code_climate:
    repo_token:
      secure: b6e1c43d0176b9d155b89984fde884694994bdf0c977ec1b88dc316d58821c8d
       chrome: stable
   

before_script: 
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
  

script:
  - npm test

after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"

notifications:
  email: false

after_success:
  - npm run coverage
  - npm run report-coverage
